
workflows:
  android-release:
    name: Build Android APK
    max_build_duration: 30
    environment:
      java: 11
    scripts:
      - echo "Running clean build..."
      - ./gradlew clean
      - ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
